@echo off
cd /D "%~dp0"
AMIDEEFIx64.exe /IVN "American Megatrends International, LLC."
AMIDEEFIx64.exe /SM "System manufacturer"
AMIDEEFIx64.exe /SP "System Product Name"
AMIDEEFIx64.exe /SV "System Version"
AMIDEEFIx64.exe /SK "SKU"
AMIDEEFIx64.exe /SS "To be filled by O.E.M."
AMIDEEFIx64.exe /SF "To be filled by O.E.M."
AMIDEEFIx64.exe /BT "Default string"
AMIDEEFIx64.exe /BLC "Default string"
AMIDEEFIx64.exe /BTH 2 "Default string"
AMIDEEFIx64.exe /BLCH 2 "Default string"
AMIDEEFIx64.exe /CM "Default string"
AMIDEEFIx64.exe /CV "Default string"
AMIDEEFIx64.exe /CA "Default string"
AMIDEEFIx64.exe /CSK "Default string"
AMIDEEFIx64.exe /CMH 3 "Default string"
AMIDEEFIx64.exe /CVH 3 "Default string"
AMIDEEFIx64.exe /CSH 3 "Default string"
AMIDEEFIx64.exe /CAH 3 "Default string"
AMIDEEFIx64.exe /CSKH 3 "Default string"
AMIDEEFIx64.exe /OS 1 "Default string"
AMIDEEFIx64.exe /OS 2 "Default string"
AMIDEEFIx64.exe /OS 3 "Default string"
AMIDEEFIx64.exe /OS 4 "Default string"
AMIDEEFIx64.exe /OS 5 "Default string"
AMIDEEFIx64.exe /OS 6 "Default string"
AMIDEEFIx64.exe /OS 7 "Default string"
AMIDEEFIx64.exe /OS 8 "Default string"
AMIDEEFIx64.exe /SCO 1 "Default string"
AMIDEEFIx64.exe /SCO 2 "Default string"
AMIDEEFIx64.exe /SCO 3 "Default string"
AMIDEEFIx64.exe /SCO 4 "Default string"
AMIDEEFIx64.exe /CS "Default string"
AMIDEEFIx64.exe /PAT "To be filled by O.E.M."
AMIDEEFIx64.exe /PSN "To be filled by O.E.M."
AMIDEEFIx64.exe /PPN "To be filled by O.E.M."
AMIDEEFIx64.exe /SU 345547456GK8256565
AMIDEEFIx64.exe /BSH 2 M80-%random%-63572826
AMIDEEFIx64.exe /BS M80-%random%-7368362
pause